[api]
enabled = true
port = 54321

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://mailflow.vercel.app"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
