services:
  frontend:
    image: 'brsoftswiss/smartis:1.1.0'
    restart: always
    environment:
      VITE_API_URL: '${VITE_SUPABASE_URL}'
      VITE_SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  default:
    name: coolify-infra
    external: true
