services:
  ocr-api:
    image: 'brsoftswiss/ocr-smartis:1.0.0'
    container_name: ocr-api
    restart: always
    ports:
      - '7996:80'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 --spider http://127.0.0.1:80/ || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  coolify:
    external: true