-- ============================================================
-- 1. Neue Felder: partner_name + partner_vorname
-- ============================================================
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS partner_name TEXT,
  ADD COLUMN IF NOT EXISTS partner_vorname TEXT;

-- ============================================================
-- 2. Import 93 Privatpersonen (Test-Import)
-- ============================================================
INSERT INTO customers (
  company_name, person_type, vorname, nachname,
  kanton, plz, ort, strasse,
  partner_name, partner_vorname, aktiv
) VALUES
  ('Sedat Durmus', 'privatperson', 'Sedat', 'Durmus', 'AG', '5436', 'Würenlos', 'Haselstrasse 5', '', '', TRUE),
  ('Lukas Breu', 'privatperson', 'Lukas', 'Breu', 'AI', '9413', 'Oberegg', 'St. Antonstrasse 34', 'Breu', 'Nadia', TRUE),
  ('Cédric Rutz', 'privatperson', 'Cédric', 'Rutz', 'AR', '9107', 'Urnäsch', 'Sulzbrunnen 891', '', '', TRUE),
  ('Werner Jakob', 'privatperson', 'Werner', 'Jakob', 'AR', '9404', 'Rorschacherberg', 'Käserenrain 18', 'Jakob', 'Claudia', TRUE),
  ('Rolf Schindler', 'privatperson', 'Rolf', 'Schindler', 'AR', '9410', 'Heiden', 'Werdstrasse 6', 'Schindler', 'Luzia', TRUE),
  ('Luzia Schindler', 'privatperson', 'Luzia', 'Schindler', 'AR', '9410', 'Heiden', 'Werdstrasse 6', '', '', TRUE),
  ('Stephan Wettler', 'privatperson', 'Stephan', 'Wettler', 'BE', '8640', 'Rapperswil', 'Etzelstrasse 5', '', '', TRUE),
  ('Daniel Lätsch', 'privatperson', 'Daniel', 'Lätsch', 'BE', '8645', 'Jona', 'Hummelbergstrasse 153', 'Lätsch', 'Monika', TRUE),
  ('Mark Laszlo Pinter', 'privatperson', 'Mark Laszlo', 'Pinter', 'BE', '3312', 'Fraubrunnen', 'Büündering 8', 'Morón', 'Sofia', TRUE),
  ('Stefan Eichenberger', 'privatperson', 'Stefan', 'Eichenberger', 'BE', '3513', 'Bigenthal', 'Künghaus 218', 'Eichenberger', 'Judith', TRUE),
  ('Stephan Wettler', 'privatperson', 'Stephan', 'Wettler', 'GL', '8640', 'Rapperswil', 'Etzelstrasse 5', '', '', TRUE),
  ('Thomas Stepan', 'privatperson', 'Thomas', 'Stepan', 'GR', '7304', 'Maienfeld', 'Im Loretscher 8', '', '', TRUE),
  ('Marc Banderet', 'privatperson', 'Marc', 'Banderet', 'GR', '9320', 'Frasnacht', 'Chriesiweg 16b', 'Banderet', 'Nicola', TRUE),
  ('Zoran Vidakovic', 'privatperson', 'Zoran', 'Vidakovic', 'SG', '9300', 'Wittenbach', 'St. Gallerstrasse 57', 'Vidakovic', 'Rajka', TRUE),
  ('Marc Schwarber', 'privatperson', 'Marc', 'Schwarber', 'SG', '9443', 'Widnau', 'Gässelistrasse 11a', 'Schwarber', 'Carmen', TRUE),
  ('Andreas Gschwend', 'privatperson', 'Andreas', 'Gschwend', 'SG', '9443', 'Widnau', 'Gässelistrasse 33', '', '', TRUE),
  ('Philippe Wyss', 'privatperson', 'Philippe', 'Wyss', 'SG', '7323', 'Wangs', 'Haldenstrasse 21', 'Wyss', 'Lia', TRUE),
  ('Dominik Bettin', 'privatperson', 'Dominik', 'Bettin', 'SG', '8880', 'Walenstadt', 'Gartenstrasse 1a', '', '', TRUE),
  ('Erich Bieler-Günther', 'privatperson', 'Erich', 'Bieler-Günther', 'SG', '7324', 'Vilters', 'Aeulistrasse 8', 'Bieler-Günther', 'Sonja', TRUE),
  ('Sonja Bieler-Günther', 'privatperson', 'Sonja', 'Bieler-Günther', 'SG', '7324', 'Vilters', 'Aeulistrasse 8', '', '', TRUE),
  ('Carlos Fonseca Marinho de Castro', 'privatperson', 'Carlos', 'Fonseca Marinho de Castro', 'SG', '9240', 'Uzwil', 'Dammhaldenstrasse 29', 'Sousa Lourenço Castro-Sousa Lourenço', 'Sonia', TRUE),
  ('Sascha Zedi', 'privatperson', 'Sascha', 'Zedi', 'SG', '8882', 'Unterterzen', 'Lehrütistrasse 10', '', '', TRUE),
  ('Peter Fehr-Streule', 'privatperson', 'Peter', 'Fehr-Streule', 'SG', '9323', 'Steinach', 'Wiedenstrasse 24', 'Fehr-Streule', 'Rosmarie', TRUE),
  ('Abdullah Boyacioglu', 'privatperson', 'Abdullah', 'Boyacioglu', 'SG', '9323', 'Steinach', 'Buchenstrasse 16b', 'Boyacioglu', 'Edina', TRUE),
  ('Rosmarie Fehr-Streule', 'privatperson', 'Rosmarie', 'Fehr-Streule', 'SG', '9323', 'Steinach', 'Wiedenstrasse 24', '', '', TRUE),
  ('Patricia Caderas', 'privatperson', 'Patricia', 'Caderas', 'SG', '9014', 'St. Gallen', 'Sittertalstrasse 28', '', '', TRUE),
  ('Manuel Anderes', 'privatperson', 'Manuel', 'Anderes', 'SG', '9014', 'St. Gallen', 'Sittertalstrasse 28', '', '', TRUE),
  ('Fabien Sieber', 'privatperson', 'Fabien', 'Sieber', 'SG', '7320', 'Sargans', 'Grünaustrasse 27', 'Sieber', 'Sonja', TRUE),
  ('Ivo Bigger', 'privatperson', 'Ivo', 'Bigger', 'SG', '7320', 'Sargans', 'Städchenstrasse 72a', 'Bigger-Cassagne', 'Elisabeth', TRUE),
  ('Ruth Stepan-Bigger', 'privatperson', 'Ruth', 'Stepan-Bigger', 'SG', '7320', 'Sargans', 'Knappenweg 2', '', '', TRUE),
  ('Christian Müller', 'privatperson', 'Christian', 'Müller', 'SG', '9404', 'Rorschacherberg', 'Obere Berglistrasse 9', 'Müller', 'Moira', TRUE),
  ('Werner Jakob', 'privatperson', 'Werner', 'Jakob', 'SG', '9404', 'Rorschacherberg', 'Käserenrain 18', 'Jakob', 'Claudia', TRUE),
  ('Pascal Wuillemin', 'privatperson', 'Pascal', 'Wuillemin', 'SG', '9404', 'Rorschacherberg', 'Thalerstrasse 121', 'Wuillemin', 'Eva', TRUE),
  ('Stefan Högger', 'privatperson', 'Stefan', 'Högger', 'SG', '9400', 'Rorschach', 'Hauptstr. 28', '', '', TRUE),
  ('Bettina Jakob', 'privatperson', 'Bettina', 'Jakob', 'SG', '9400', 'Rorschach', 'Löwengartenstrasse 36', '', '', TRUE),
  ('David Henschel', 'privatperson', 'David', 'Henschel', 'SG', '9445', 'Rebstein', 'Bettenstr. 11', 'Henschel', 'Brigitte', TRUE),
  ('Franco Mora', 'privatperson', 'Franco', 'Mora', 'SG', '8640', 'Rapperswil', 'Oberseestrasse 69', '', '', TRUE),
  ('Stephan Wettler', 'privatperson', 'Stephan', 'Wettler', 'SG', '8640', 'Rapperswil', 'Etzelstrasse 5', '', '', TRUE),
  ('Peter Stepan', 'privatperson', 'Peter', 'Stepan', 'SG', '8887', 'Mels', 'Grossfeldstrasse 14', '', '', TRUE),
  ('Angela Wohlwend', 'privatperson', 'Angela', 'Wohlwend', 'SG', '8887', 'Mels', 'Grossfeldstrasse 14', '', '', TRUE),
  ('Daniel Lätsch', 'privatperson', 'Daniel', 'Lätsch', 'SG', '8645', 'Jona', 'Hummelbergstrasse 153', 'Lätsch', 'Monika', TRUE),
  ('Ryan Schenkel', 'privatperson', 'Ryan', 'Schenkel', 'SG', '8645', 'Jona', 'Kiebitzstrasse 57', '', '', TRUE),
  ('Sonja Mora-Pilger', 'privatperson', 'Sonja', 'Mora-Pilger', 'SG', '8645', 'Jona', 'Bildaustrasse 37', '', '', TRUE),
  ('Marco Russo', 'privatperson', 'Marco', 'Russo', 'SG', '9200', 'Gossau', 'Zeughausstrasse 23', 'Russo', 'Ursula', TRUE),
  ('Fabian Sommer', 'privatperson', 'Fabian', 'Sommer', 'SG', '9403', 'Goldach', 'Am Rebberg 16', 'Sommer', 'Manuela', TRUE),
  ('Dominik Schenkel', 'privatperson', 'Dominik', 'Schenkel', 'SG', '8714', 'Feldbach', 'Morgensonne 1', 'Schenkel', 'Biljana', TRUE),
  ('Balz Hug', 'privatperson', 'Balz', 'Hug', 'SG', '9642', 'Ebnat-Kappel', 'Ackerhusweg 122', 'Hug', 'Andrea', TRUE),
  ('Sascha Bigger', 'privatperson', 'Sascha', 'Bigger', 'SG', '9444', 'Diepoldsau', 'Sandstrasse 3', '', '', TRUE),
  ('Jan Stäheli', 'privatperson', 'Jan', 'Stäheli', 'SG', '9014', 'Bruggen', 'Aetschbergstrasse 23b', '', '', TRUE),
  ('Daniel Stüble', 'privatperson', 'Daniel', 'Stüble', 'SG', '9304', 'Bernhardzell', 'Ruezenwil 1030', 'Stüble', 'Kerstin', TRUE),
  ('Christof Schwarber', 'privatperson', 'Christof', 'Schwarber', 'SG', '9434', 'Au', 'Mennweg 3', 'Schwarber', 'Cornelia', TRUE),
  ('Marco Cantele', 'privatperson', 'Marco', 'Cantele', 'SZ', '8832', 'Wollerau', 'Steinbruchweg 13', 'Matthews', 'Fiona', TRUE),
  ('Sandro Eigenmann', 'privatperson', 'Sandro', 'Eigenmann', 'TG', '9315', 'Winden', 'Kreuzstrasse 13', '', '', TRUE),
  ('David Zehentmayer', 'privatperson', 'David', 'Zehentmayer', 'TG', '9315', 'Winden', 'Bahnhofstrasse 8', 'Zehentmayer-Beck', 'Sabrina', TRUE),
  ('Nicole Cangina', 'privatperson', 'Nicole', 'Cangina', 'TG', '9507', 'Stettfurt', 'Weinbergstrasse 18', '', '', TRUE),
  ('Abdullah Boyacioglu', 'privatperson', 'Abdullah', 'Boyacioglu', 'TG', '9323', 'Steinach', 'Buchenstrasse 16b', 'Boyacioglu', 'Edina', TRUE),
  ('Nicola Roth', 'privatperson', 'Nicola', 'Roth', 'TG', '9320', 'Stachen', 'Lehgasse 12', '', '', TRUE),
  ('Klara Aerne-Künzle', 'privatperson', 'Klara', 'Aerne-Künzle', 'TG', '9320', 'Stachen', 'Haselweg 1', '', '', TRUE),
  ('Marius Bodensohn', 'privatperson', 'Marius', 'Bodensohn', 'TG', '9320', 'Stachen', 'St. Gallerstrasse 228', '', '', TRUE),
  ('Martin Aerne', 'privatperson', 'Martin', 'Aerne', 'TG', '9320', 'Stachen', 'Lehgasse 12', '', '', TRUE),
  ('Sandra Roth', 'privatperson', 'Sandra', 'Roth', 'TG', '9320', 'Stachen', 'Lehgasse 12', '', '', TRUE),
  ('Werner Jakob', 'privatperson', 'Werner', 'Jakob', 'TG', '9404', 'Rorschacherberg', 'Käserenrain 18', 'Jakob', 'Claudia', TRUE),
  ('Sandra Berenbold', 'privatperson', 'Sandra', 'Berenbold', 'TG', '8590', 'Romanshorn', 'Sonnmattstrasse 3a', '', '', TRUE),
  ('Joëlle Banderet', 'privatperson', 'Joëlle', 'Banderet', 'TG', '9325', 'Roggwil', 'Vorderau 4', '', '', TRUE),
  ('Richard Weng', 'privatperson', 'Richard', 'Weng', 'TG', '9325', 'Roggwil', 'Schulweg 2', 'Weng', 'Corinna', TRUE),
  ('Gabriel Gassmann', 'privatperson', 'Gabriel', 'Gassmann', 'TG', '9315', 'Neukirch', 'Haldenweg 8', 'Gassmann-Füchslin', 'Beatrice', TRUE),
  ('Stepanka Strähl', 'privatperson', 'Stepanka', 'Strähl', 'TG', '8555', 'Müllheim', 'Bahnhofstr. 12', '', '', TRUE),
  ('Silvan Nyffenegger', 'privatperson', 'Silvan', 'Nyffenegger', 'TG', '8280', 'Kreuzlingen', 'Gartenstrasse 2e', '', '', TRUE),
  ('Gabriele Griessenböck', 'privatperson', 'Gabriele', 'Griessenböck', 'TG', '8280', 'Kreuzlingen', 'Schützenstrasse 27', '', '', TRUE),
  ('Marcelo Correia Pires', 'privatperson', 'Marcelo', 'Correia Pires', 'TG', '8280', 'Kreuzlingen', 'Breitenäckerliweg 2A', 'De Sousa Lavos Matos', 'Joana', TRUE),
  ('Marc Banderet', 'privatperson', 'Marc', 'Banderet', 'TG', '9320', 'Frasnacht', 'Schulstr. 9', '', '', TRUE),
  ('Benjamin Köster', 'privatperson', 'Benjamin', 'Köster', 'TG', '9320', 'Frasnacht', 'Buchhorn 46', 'Köster', 'Marline', TRUE),
  ('Dieter-Jan Janout', 'privatperson', 'Dieter-Jan', 'Janout', 'TG', '9320', 'Frasnacht', 'Buchhorn 47', 'Michaela', 'Galante-Janout', TRUE),
  ('Roland Inäbnit-Schneider', 'privatperson', 'Roland', 'Inäbnit-Schneider', 'TG', '8586', 'Engishofen', 'Aachstrasse 11', 'Inäbnit-Schneider', 'Edith', TRUE),
  ('Ursula Näf', 'privatperson', 'Ursula', 'Näf', 'TG', '9322', 'Egnach', 'Wilenstrasse 5', '', '', TRUE),
  ('Heinz Nyffenegger', 'privatperson', 'Heinz', 'Nyffenegger', 'TG', '9320', 'Arbon', 'Brühlstrasse 11', '', '', TRUE),
  ('Christoph Wanner', 'privatperson', 'Christoph', 'Wanner', 'TG', '9320', 'Arbon', 'Alemannstrasse 13', '', '', TRUE),
  ('Gottschling Georg', 'privatperson', 'Gottschling', 'Georg', 'TG', '9320', 'Arbon', 'Romanshornerstr. 32', 'Ute', 'Gottschling', TRUE),
  ('Veit Sturm', 'privatperson', 'Veit', 'Sturm', 'TG', '9320', 'Arbon', 'Weinbergstrasse 8', 'Zawinka', 'Claudia', TRUE),
  ('Jill Hoenner', 'privatperson', 'Jill', 'Hoenner', 'TG', '9320', 'Arbon', 'Alemannenstrasse 13', '', '', TRUE),
  ('Martin Küppers', 'privatperson', 'Martin', 'Küppers', 'TG', '9320', 'Arbon', 'Am See 5', 'Hong', 'Luo', TRUE),
  ('Augusta Tanner-Roman', 'privatperson', 'Augusta', 'Tanner-Roman', 'TG', '9320', 'Arbon', 'Rebenstrasse 19a', '', '', TRUE),
  ('Ayllen Roth', 'privatperson', 'Ayllen', 'Roth', 'TG', '9320', 'Arbon', 'Lehgasse 12', '', '', TRUE),
  ('Denise Salathé', 'privatperson', 'Denise', 'Salathé', 'TG', '9320', 'Arbon', 'Brühlstrasse 11', '', '', TRUE),
  ('Max Lutz', 'privatperson', 'Max', 'Lutz', 'TG', '9320', 'Arbon', 'Berglistr. 28', 'Lutz', 'Brigitta', TRUE),
  ('Veit Sturm', 'privatperson', 'Veit', 'Sturm', 'TG', '9320', 'Arbon', 'Weinbergstrasse 8', 'Zawinka', 'Claudia', TRUE),
  ('Nicola Banderet', 'privatperson', 'Nicola', 'Banderet', 'TG', '9320', 'Arbon', 'St. Gallerstrasse 42a', '', '', TRUE),
  ('Stephan Wettler', 'privatperson', 'Stephan', 'Wettler', 'TI', '8640', 'Rapperswil', 'Etzelstrasse 5', '', '', TRUE),
  ('Marc Banderet', 'privatperson', 'Marc', 'Banderet', 'TI', '9320', 'Frasnacht', 'Chriesiweg 16b', 'Banderet', 'Nicola', TRUE),
  ('Stephan Wettler', 'privatperson', 'Stephan', 'Wettler', 'ZH', '8640', 'Rapperswil', 'Etzelstrasse 5', '', '', TRUE),
  ('Daniel Lätsch', 'privatperson', 'Daniel', 'Lätsch', 'ZH', '8645', 'Jona', 'Hummelbergstrasse 153', 'Lätsch', 'Monika', TRUE),
  ('Dominik Schenkel', 'privatperson', 'Dominik', 'Schenkel', 'ZH', '8714', 'Feldbach', 'Morgensonne 1', 'Schenkel', 'Biljana', TRUE),
  ('Suat Durmus', 'privatperson', 'Suat', 'Durmus', 'ZH', '8953', 'Dietikon', 'Ligusterstrasse 3', 'Durmus-Cantay', 'Nurcan', TRUE);